
= Murat Yaman

== Geliştirilen Uygulamadaki Görev


. Splash Screen
. Login with Web service
. Tap Slider
.. Durum bildirne (Tab_SendSmsAndLocation)
.. Arama (Tab_Call)
.. Acil Birim ekleme (Tab_User)
. Pager Adapter
. Maps Activity
. Location Service
. kamera ile Görüntü alma
. Web Service


=== 1)Splash Screen

1. Uygulamanın açılması ile başlayan ufak bir zaman dilimi ile kullanıcıya
uygulama ile ilgili bir tanıtım,logo vb bir ekranı gösterme.

[source , java  ]
-----
public class SplashActivity extends Activity {


    private static int SPLASH_TIME_OUT = 1000;    <1>
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_splash);
        startHandler();

    }
    public void startHandler(){

        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {

                intetLogin  =new Intent(getApplicationContext(),Login.class);
                 startActivity(intetLogin);

                finish();
            }
        }, SPLASH_TIME_OUT);
    }

}
-----

Thread yardimi ile ile 1. sn lik bir beklemenin ardindan gecis islemini gerceklestiriyoruz .
 <1>  ile Belirttilen Kod parcasinda bekleme milisaniyesini yaziyoruz


=== 2)Login with Web service

2. Uygulamada Guvenlik amaçlı uygulama kullanıcısının kişisel bilgileri Login Ekranında
 alınıp  Bakanlıgın Saglamıs Oldugu WebService Sayesinde
https://tckimlik.nvi.gov.tr/Service/KPSPublic.asmx/ Uygulama kullanıcısının TC Cumhiyeti vatandaşı olduğu kontrol edilerek uygulamaya giriş yapmasına izin verilir.

=== uygulama kodları .
[source ,java]
----

/**
 * Created by murat on 09.04.2016.
 */
public class Login extends AppCompatActivity {

    private  static  final String NAMESPACE_TC ="http://tckimlik.nvi.gov.tr/WS";
    private  static  final String SERVİCEURL_TC ="https://tckimlik.nvi.gov.tr/Service/KPSPublic.asmx";
    private  static  final String METHODNAME_TC ="TCKimlikNoDogrula";
    private  static  final String SOAPACTION_TC="http://tckimlik.nvi.gov.tr/WS/TCKimlikNoDogrula";

    public class MyAsyncTask extends AsyncTask<String, Void, String> {


        private final ProgressDialog dialog = new ProgressDialog(Login.this);
        @Override
        protected void onPreExecute() {
            this.dialog.setMessage("Kontrol ediliyor...");
            this.dialog.show();
        }
        @Override
        protected void onPostExecute(String sonuc) {
            try {
                 donen=sonuc;
                if (sonuc != null) {
                    Log.d(TAG, "onPostExecute: Sonuc "+sonuc);
                    if (sonuc.equals("true")){
                        Intent i=new Intent(getApplicationContext(),MainActivity.class);
                        startActivity(i);
                    }
            }catch (Exception e){ }
        }
        @Override
        protected String doInBackground(String... params) {
            String son = "";

            son= ControlUserID(); <1>
            return son;
        }
    };

    <2>
    public String ControlUserID() {

        String responseValue = "";
        SoapObject request = new SoapObject(NAMESPACE_TC, METHODNAME_TC);
        request.addProperty("TCKimlikNo", Long.valueOf(userID.getText().toString()));
        request.addProperty("Ad",userName.getText().toString().toUpperCase().trim());
        request.addProperty("Soyad",lastName.getText().toString().toUpperCase().trim());
        request.addProperty("DogumYili",Integer.valueOf(userAge.getText().toString().trim()));

        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(
                SoapEnvelope.VER11);
        soapEnvelope.dotNet = true;
        soapEnvelope.setOutputSoapObject(request);
        HttpTransportSE ahtSE = new HttpTransportSE(SERVİCEURL_TC);
        try {
            ahtSE.call(SOAPACTION_TC, soapEnvelope);
        } catch (IOException e) {

            e.printStackTrace();

        } catch (XmlPullParserException e) {
            e.printStackTrace();
        }
        try {
            //karşıdan gelen response degirini alma (true ,false)
            responseValue = ""+(SoapPrimitive) soapEnvelope.getResponse();
            Log.d(TAG,responseValue);
        } catch (SoapFault e) {
            e.printStackTrace();
        }
        return responseValue;
    }
}

----

<1>  bu alanda kullanıcının girdiği kişi bilgileri dogrulanmak için tanımlanmıs olan metoda gonderiliyor ve sonuç onPostExecute metoduna dondürülüyor.
<2>  kisi bilgileri web service yardımı ile dogrulanır.

== 3)Tap Slider

Uygulamada Farklı ekranlar (Durum bildirme ,Arama ,Acil birim Eklem) Arasında Geçiş yapmayı sağlamak için Tab Slider Yapısı kullanıldı.
Bunun için eklemek istediginiz her tap için bir sınıf eklenir .



=== Tab_SendSmsAndLocation
[source,java]
----
public class Tab_SendSmsAndLocation extends Fragment
----
=== Tab_Call
[source,java]
----
public class Tab_Call extends Fragment
----

=== Tab_user
[source,java]
----
public class Tab_User extends Fragment
----


== 4)Tab_PagerAdapter

Tanımladığımız sınıflar için bir Adapter Sınıfına ihtiyacımız olcak bunun için :

[source,java]
----
public class Tab_PagerAdapter extends FragmentStatePagerAdapter {
    int mNumOfTabs;

    public Tab_PagerAdapter(FragmentManager fm, int NumOfTabs) {
        super(fm);
        this.mNumOfTabs = NumOfTabs;
    }

    @Override
    public Fragment getItem(int position) {

        switch (position) {
            case 0:
                Tab_SendSmsAndLocation tab1 = new Tab_SendSmsAndLocation();
                return tab1;
            case 1:
                Tab_Call tab2 = new Tab_Call();
                return tab2;
            case 2:
               Tab_User tab3 = new Tab_User();
               return tab3;
            default:
                return null;
        }
    }

    @Override
    public int getCount() {
        return mNumOfTabs;
    }
}
----
**
Ekledigimiz clasları daha sonradasında Main.Activiy Klasımız da  Aşağıdaki tanımlama ile tanımlı hale getiriyoruz .
**
[source, java]
 ----
        tabLayout.addTab(tabLayout.newTab().setCustomView(setIconText(R.drawable.send_mssage_ki_b, sms)));
        tabLayout.addTab(tabLayout.newTab().setCustomView(setIconText(R.drawable.call_ki_b ,call)));
        tabLayout.addTab(tabLayout.newTab().setCustomView(setIconText(R.drawable.user_ki_b, user)));
----



=== 5 ) Maps Activity
5 Maps Activity Kullanıcının anlık olarak bulunduğu konumunu ve konumunun Adresini bildirmek için kullanılmıştır
LocationServiceden Aldığı enlem ve boylam degeri sayasinde işlevini yerine getirebilmektedir.

[source, java]
----

public class MapsActivity extends FragmentActivity implements OnMapReadyCallback {

    //Location Serviceden Aldığı Degerler sayesinde Konumu haritaya basar.
    @Override
    public void onMapReady(GoogleMap googleMap) {

        LatLng location = new LatLng(locationService.getLatitude(), locationService.getLongitude());
        mMap.addMarker(new MarkerOptions().position(location).title("Konumunuz"));
        mMap.moveCamera(CameraUpdateFactory.newLatLng(location));

        CameraUpdate yourLocation = CameraUpdateFactory.newLatLngZoom(location, 15);
        mMap.animateCamera(yourLocation);

        adress=getCompleteAddressString(latitude, longitude);

        Snackbar snackbar = Snackbar.make(c, adress.toString(), Snackbar.LENGTH_INDEFINITE);
        snackbar.show();
    }

    //Aldıgı enlem boylam degerleri sayesinde adress bilgisini dondorür
    private String getCompleteAddressString(double LATITUDE, double LONGITUDE) {
        String strAdd = "";
        Geocoder geocoder = new Geocoder(this, Locale.getDefault());
        try {
            List<Address> addresses = geocoder.getFromLocation(LATITUDE, LONGITUDE, 1);
            if (addresses != null) {
                Address returnedAddress = addresses.get(0);
                StringBuilder strReturnedAddress = new StringBuilder("");

                for (int i = 0; i < returnedAddress.getMaxAddressLineIndex(); i++) {
                    strReturnedAddress.append(returnedAddress.getAddressLine(i)).append("\n");
                }
                strAdd = strReturnedAddress.toString();
                Log.d(TAG, "getCompleteAddressString: " + strReturnedAddress.toString());
            } else {
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return strAdd;
    }
}

----

== 6) Location Service
 Location Service ile GPS ve Ag yardımı ile Anlık olarka Bulundugumuz yerin
 Kordinatlarını alıp Acil durum bildirimlerinde ve kullanıcının konumunu,
 adresini bulmada kullanılır.


 verilen iki metod ile enlem boylam degeri alınır.


[source, java]

----
public double getLatitude(){
         if(location != null){
             latitude = location.getLatitude();
         }
         return latitude;
     }

      public double getLongitude(){
              if(location != null){
                  longitude = location.getLongitude();
              }
              return longitude;
          }
----


== 7) kamera ile Görüntü alma
Uygulamada acil durum bildirimlerde olay ile ilgili fotograf alabilmek için eklenmiştir.

[source ,java]
----

/**
 * Created by murat on 01.05.2016.
 */
public class Camera extends AppCompatActivity {


    private static final int CAMERA_REQUEST = 1888;

    <1>
    public void takeImageFromCamera(View view) {
        Intent cameraIntent = new Intent(android.provider.MediaStore.ACTION_IMAGE_CAPTURE);
        startActivityForResult(cameraIntent, CAMERA_REQUEST);
    }
    <2>
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == CAMERA_REQUEST && resultCode == RESULT_OK) {
            Bitmap mphoto = (Bitmap) data.getExtras().get("data");
            encodedImageData =getEncoded64ImageStringFromBitmap(mphoto);
            String brm = bundle.getString("birim");
            String msj =bundle.getString("mesaj");
            new WebService(getApplicationContext()).execute(brm,konum, msj, encodedImageData);
            Intent i =new Intent(getApplicationContext(),MainActivity.class);
            startActivity(i);
            mimageView.setImageBitmap(mphoto);
        }
    }

    <3>
    public String getEncoded64ImageStringFromBitmap(Bitmap bitmap) {
        ByteArrayOutputStream stream = new ByteArrayOutputStream();
        bitmap.compress(Bitmap.CompressFormat.JPEG, 70, stream);
        byte[] byteFormat = stream.toByteArray();
        // get the base 64 string
        String imgString = Base64.encodeToString(byteFormat, Base64.NO_WRAP);

        return imgString;
    }
}

----
<1> Kameradan görüntü almak için istek yapılır .
<2> yapılan istek sonucu resim çekilir ve resim datası alınır .base64 formatına döndürmek için 3 numaralı metoda yollanır.
<3> Bitmap formatında alınan resmi Base64 formatına dondürür.


== 9) Web Service



**
Uygulamada Yaptığımız tüm acil birim çagrılarını burada tanımladığımız web service göndererek web tarafında weri tabanında kayıt altına alınır .
hemen sonrasın da veriler  veritabanından çekilerek Web tarafında(http://www.yamankod.com/durumum_acil/ ) Birim ' e gösteriyor .
**
[source ,java]


----

public class WebService extends AsyncTask<String ,Void,String> {

    @Override
    protected String doInBackground(String... params) {
       // replace with your url
        String reg_url ="http://yamankod.com/durumum_acil/service.php";
        //Date & Time
        Calendar c = Calendar.getInstance();
        jsonObject = new JSONObject();

        try {
             httpClient = new DefaultHttpClient();
             httpPost = new HttpPost(reg_url);

            jsonObject.put("birim", brm);
            jsonObject.put("konum", knm);
            jsonObject.put("mesaj", msj);
            jsonObject.put("resim", rsm);
            jsonObject.put("tarih", c.get(Calendar.YEAR)+"-"+(c.get(Calendar.MONTH)+1)+"-"+c.get(Calendar.DATE)+"-"+c.get((Calendar.HOUR_OF_DAY))+"-"+c.get(Calendar.MINUTE));

            nameValuePair = new ArrayList<NameValuePair>(1);
            nameValuePair.add(new BasicNameValuePair("parametre", jsonObject.toString()));

        } catch (JSONException e) {e.printStackTrace();}
        try {
            httpPost.setEntity(new UrlEncodedFormEntity(nameValuePair));
        } catch (UnsupportedEncodingException e) {e.printStackTrace();}
        //making POST request.
        try {
            HttpResponse response = httpClient.execute(httpPost);
            Log.d("Http Post Response:", response.toString());

        } catch (ClientProtocolException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    @Override
    protected void onPostExecute(String results) {
        this.dialog.dismiss();
    }

}

-----